-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 23:03:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `account`;
USE `account`;
-- -----------------------------------------------------
-- Table `ARMAZENADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARMAZENADOR` ;

CREATE TABLE IF NOT EXISTS `ARMAZENADOR` (
  `idSenha` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `SenhaArmazenada` VARCHAR(16) NULL,
  `CONTA_idConta` INT NOT NULL,
  PRIMARY KEY (`idSenha`, `CONTA_idConta`),
  CONSTRAINT `fk_ARMAZENADOR_CONTA`
    FOREIGN KEY (`CONTA_idConta`)
    REFERENCES `CONTA` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ARMAZENADOR_CONTA_idx` ON `ARMAZENADOR` (`CONTA_idConta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CONTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CONTA` ;

CREATE TABLE IF NOT EXISTS `CONTA` (
  `idConta` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(16) NULL,
  `Nome` VARCHAR(45) NULL,
  `USUARIO_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idConta`, `USUARIO_idUsuario`),
  CONSTRAINT `fk_CONTA_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CONTA_USUARIO1_idx` ON `CONTA` (`USUARIO_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
